# Generated by Django 3.0.5 on 2020-04-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseType', models.TextField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
